<?xml version="1.0"?>
<package format="3">
  <name>ug_ui</name>
  <version>0.1.0</version>
  <description>PyQt5 graphical user interface for the Universal Gripper</description>

  <maintainer email="joseph.polania@uni.lu">Joseph Polania</maintainer>

  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>ug_interfaces</depend>

  <exec_depend>python3-pyqt5</exec_depend>
  <exec_depend>python3-pyqtgraph</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
